In [20]:
import numpy as np
import pandas as pd

In [34]:
player_stats=np.array([[175,80,90],[150,76,86],[165,80,75]])
max_point_index=np.argmax(player_stats[:,2])
player_stats[max_point_index,1]=80
new_player=[165,87,78]
player_stats=np.vstack([player_stats,new_player])
new_stats=[160,65,78]
insert_index=2
player_stats=np.insert(player_stats,insert_index,new_stats,axis=0)
min_points_index=np.argmin(player_stats[:,2])
player_stats=np.delete(player_stats,min_points_index,axis=0)
print("Player Stats:"'\n',player_stats)

Player Stats:
 [[175  80  90]
 [150  76  86]
 [160  65  78]
 [165  87  78]]


In [35]:
purchase_amount=np.array([100,200,300,400])
item_count=np.array([1,2,3,4])
shallow_copy=purchase_amount.view()
deep_copy=item_count.copy()
concatenated_array=np.concatenate((purchase_amount,item_count))
split_condition=concatenated_array>150
greater_than_150=concatenated_array[split_condition]
less_than_150=concatenated_array[~split_condition]
purchase_amount[0]=120
item_count[0]=10
print("Shallow_Copy:"'\n',shallow_copy)
print("Deep_Copy:"'\n',deep_copy)
print("Concatenated_Array:"'\n',concatenated_array)
print("Greater Than 150:"'\n',greater_than_150)
print("Less than 150:"'\n',less_than_150)



Shallow_Copy:
 [120 200 300 400]
Deep_Copy:
 [1 2 3 4]
Concatenated_Array:
 [100 200 300 400   1   2   3   4]
Greater Than 150:
 [200 300 400]
Less than 150:
 [100   1   2   3   4]
